/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Clidren Routes

const AboutLazyImport = createFileRoute('/about')()
const SettingsLazyImport = createFileRoute('/settings')()
const LogsLazyImport = createFileRoute('/logs')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings').then((d) => d.Route))

const LogsLazyRoute = LogsLazyImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logs').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexLazyImport
            parentRoute: typeof rootRoute
        }
        '/logs': {
            id: '/logs'
            path: '/logs'
            fullPath: '/logs'
            preLoaderRoute: typeof LogsLazyImport
            parentRoute: typeof rootRoute
        }
        '/settings': {
            id: '/settings'
            path: '/settings'
            fullPath: '/settings'
            preLoaderRoute: typeof SettingsLazyImport
            parentRoute: typeof rootRoute
        }
        '/about': {
            id: '/about'
            path: '/about'
            fullPath: '/about'
            preLoaderRoute: typeof AboutLazyImport
            parentRoute: typeof rootRoute
        }
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexLazyRoute
    '/logs': typeof LogsLazyRoute
    '/settings': typeof SettingsLazyRoute
    '/about': typeof AboutLazyRoute
}

export interface FileRoutesByTo {
    '/': typeof IndexLazyRoute
    '/logs': typeof LogsLazyRoute
    '/settings': typeof SettingsLazyRoute
    '/about': typeof AboutLazyRoute
}

export interface FileRoutesById {
    __root__: typeof rootRoute
    '/': typeof IndexLazyRoute
    '/logs': typeof LogsLazyRoute
    '/settings': typeof SettingsLazyRoute
    '/about': typeof AboutLazyRoute
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/' | '/logs' | '/settings' | '/about'
    fileRoutesByTo: FileRoutesByTo
    to: '/' | '/logs' | '/settings' | '/about'
    id: '__root__' | '/' | '/logs' | '/settings' | '/about'
    fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
    IndexLazyRoute: typeof IndexLazyRoute
    LogsLazyRoute: typeof LogsLazyRoute
    SettingsLazyRoute: typeof SettingsLazyRoute
    AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
    IndexLazyRoute: IndexLazyRoute,
    LogsLazyRoute: LogsLazyRoute,
    SettingsLazyRoute: SettingsLazyRoute,
    AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
